export const doctors = [
    {
        id: 1,
        first_name: "Emiline",
        last_name: "McClune",
        email: "emcclune0@xrea.com",
        gender: "Female",
        adress: "zahrouni",
        tel: 52148158,
    },
    {
        id: 2,
        first_name: "Felix",
        last_name: "Ingleston",
        email: "fingleston1@hibu.com",
        gender: "Female",
        adress: "bardo",
        tel: 54816515,
    },
    {
        id: 3,
        first_name: "Travus",
        last_name: "Bergstram",
        email: "tbergstram2@pbs.org",
        gender: "Female",
        adress: "bab el khadra",
        tel: 56781648,
    },
    {
        id: 4,
        first_name: "Holly-anne",
        last_name: "Knighton",
        email: "hknighton3@booking.com",
        gender: "Female",
        adress: "hay naser",
        tel: 50524791,
    },
    {
        id: 5,
        first_name: "Sollie",
        last_name: "Naulty",
        email: "snaulty4@hud.gov",
        gender: "Male",
        adress: "zagwen",
        tel: 56894291,
    },
    {
        id: 6,
        first_name: "Annie",
        last_name: "Cockayme",
        email: "acockayme5@tuttocitta.it",
        gender: "Male",
        adress: "benzart",
        tel: 57916812,
    },
    {
        id: 7,
        first_name: "Celinda",
        last_name: "Sharvill",
        email: "csharvill6@narod.ru",
        gender: "Male",
        adress: "tborba",
        tel: 94151826,
    },
    {
        id: 8,
        first_name: "Lamond",
        last_name: "Ricket",
        email: "lricket7@washington.edu",
        gender: "Male",
        adress: "mabouba",
        tel: 90215815,
    },
    {
        id: 9,
        first_name: "Florida",
        last_name: "Licciardiello",
        email: "flicciardiello8@sina.com.cn",
        gender: "Female",
        adress: "gasrin",
        tel: 97425915,
    },
    {
        id: 10,
        first_name: "Gerianne",
        last_name: "Jonas",
        email: "gjonas9@typepad.com",
        gender: "Female",
        adress: "jandouba",
        tel: 99181541,
    },
    {
        id: 11,
        first_name: "Amy",
        last_name: "Tarbath",
        email: "atarbatha@t.co",
        gender: "Male",
        adress: "bou mhal",
        tel: 42548916,
    },
    {
        id: 12,
        first_name: "Jerrilyn",
        last_name: "Devil",
        email: "jdevilb@upenn.edu",
        gender: "Male",
        adress: "mahdeya",
        tel: 55186325,
    },
];

export const patient = [
    {
        id: 230,
        first_name: "Hank",
        last_name: "Sheara",
        email: "hsheara6d@latimes.com",
        gender: "Female",
        adress: "hay zouhour",
        tel: 56159753,
        num: 1572,
        num2: 28412,
        date: "25/7/1990",
        state: "ajout",
    },
    {
        id: 231,
        first_name: "Louisa",
        last_name: "Twidell",
        email: "ltwidell6e@salon.com",
        gender: "Female",
        adress: "mornageya",
        tel: 20486259,
        num: 2865,
        date: "05/8/1995",
        num2: 28412,
        state: "ajout",
    },
    {
        id: 232,
        first_name: "Grantham",
        last_name: "Howard",
        email: "ghoward6f@wunderground.com",
        gender: "Female",
        adress: "nevza",
        tel: 23597159,
        num: 1672,
        date: "26/7/2000",
        num2: 28412,
        state: "ajout",
    },
    {
        id: 233,
        first_name: "Christal",
        last_name: "Seid",
        email: "cseid6g@indiegogo.com",
        gender: "Genderf,luid",
        adress: "gafsa",
        tel: 21489357,
        num: 1548,
        date: "31/10/1998",
        num2: 28412,
        state: "ajout",
    },
    {
        id: 234,
        first_name: "Cristine",
        last_name: "McMillan",
        email: "cmcmillan6h@ucla.edu",
        gender: "Female",
        adress: "tabarka",
        tel: 23657894,
        date: "30/11/1990",
        num: 975825,
        state: "ajout",
    },
];

export const doctorProfile = []

export const patientProfile = [];

export const patientDossiers = [];

export const patientDossiers2 = [
    {
        id: 230,
        Dossiers: [
            {
                nomEtPrenomPatient: "Hank",
                nomEtPrenomMedecin: "mahdi ben chadya",
                numeroDossier: 18926,
                date: "27/3/2005",
                type: "finsi",
                raisonVisite: "fhiop",
                historique: "mphjad",
                medicaments: "fervex",
                consultation: "hjjklhg",
            },

            {
                nomEtPrenomPatient: "Hank",
                nomEtPrenomMedecin: "salma kamoun",
                numeroDossier: 82515,
                date: "02/05/2015",
                type: "finsi",
                raisonVisite: "fhiop",
                historique: "mphjad",
                medicaments: "fervex",
                consultation: "hjjklhg",
            },

            {
                nomEtPrenomPatient: "Hank",
                nomEtPrenomMedecin: "kabil hajji",
                numeroDossier: 57895,
                date: "08/12/2010",
                type: "finsi",
                raisonVisite: "fhiop",
                historique: "mphjad",
                medicaments: "fervex",
                consultation: "hjjklhg",
            },
        ],
    },
    {
        id: 231,
        Dossiers: [
            {
                nomEtPrenomPatient: "Louisa",
                nomEtPrenomMedecin: "salma kamoun",
                numeroDossier: 78945,
                date: "20/3/2015",
                type: "finsi",
                raisonVisite: "fhiop",
                historique: "mphjad",
                medicaments: "aspegic",
                consultation: "hjjklhg",
            },
        ],
    },
    {
        id: 232,
        Dossiers: [
            {
                nomEtPrenomPatient: "Grantham",
                nomEtPrenomMedecin: "kabil hajji",
                numeroDossier: 39545,
                date: "30/7/2020",
                type: "finsi",
                raisonVisite: "fhiop",
                historique: "mphjad",
                medicaments: "fervex",
                consultation: "hjjklhg",
            },
        ],
    },
    {
        id: 233,
        Dossiers: [
            {
                nomEtPrenomPatient: "Christal",
                nomEtPrenomMedecin: "mohsen nefsi",
                numeroDossier: 17954,
                date: "30/12/1980",
                type: "finsi",
                raisonVisite: "fhiop",
                historique: "mphjad",
                medicaments: "fervex",
                consultation: "hjjklhg",
            },
        ],
    },
    {
        id: 234,
        Dossiers: [
            {
                nomEtPrenomPatient: "Cristine",
                nomEtPrenomMedecin: "hamida welmi",
                numeroDossier: 69841,
                date: "1/6/2013",
                type: "finsi",
                raisonVisite: "fhiop",
                historique: "mphjad",
                medicaments: "fervex",
                consultation: "hjjklhg",
            },
        ],
    },
];

export const patients = [];
